export default [
  { name: 'العربية', enName: 'Arabic', code: 'ar' },
  { name: 'Azərbaycanca', enName: 'Azerbaijani', code: 'az' },
  { name: 'Deutsch', enName: 'German', code: 'de' },
  { name: 'Español', enName: 'Spanish', code: 'es' },
  { name: 'فارسی', enName: 'Persian', code: 'fa' },
  {
    name: 'Français',
    enName: 'French',
    code: 'fr',
    corePages: 'Pages Fondamentales',
    nextSteps: 'Étapes suivantes',
  },
  { name: 'עברית', enName: 'Hebrew', code: 'he' },
  { name: 'हिन्दी', enName: 'Hindi', code: 'hi' },
  { name: 'magyar', enName: 'Hungarian', code: 'hu' },
  { name: 'Bahasa Indonesia', enName: 'Indonesian', code: 'id' },
  { name: 'Italiano', enName: 'Italian', code: 'it' },
  { name: '日本語', enName: 'Japanese', code: 'ja' },
  { name: '한국어', enName: 'Korean', code: 'ko' },
  { name: 'Монгол хэл', enName: 'Mongolian', code: 'mn' },
  { name: 'Polski', enName: 'Polish', code: 'pl' },
  { name: 'Português do Brasil', enName: 'Portuguese (Brazil)', code: 'pt-BR' },
  { name: 'Русский', enName: 'Russian', code: 'ru' },
  { name: 'Türkçe', enName: 'Turkish', code: 'tr' },
  { name: 'Українська', enName: 'Ukrainian', code: 'uk' },
  { name: 'Tiếng Việt', enName: 'Vietnamese', code: 'vi' },
  { name: '简体中文', enName: 'Simplified Chinese', code: 'zh-hans' },
  { name: '繁體中文', enName: 'Traditional Chinese', code: 'zh-hant' },
]
