export default [
  { name: 'العربية', enName: 'Arabic', code: 'ar' },
  { name: 'Azərbaycanca', enName: 'Azerbaijani', code: 'az' },
  { name: 'Български', enName: 'Bulgarian', code: 'bg' },
  { name: 'বাংলা', enName: 'Bengali', code: 'bn' },
  { name: 'Deutsch', enName: 'German', code: 'de' },
  { name: 'ελληνικά', enName: 'Greek', code: 'el' },
  { name: 'Español', enName: 'Spanish', code: 'es', issueNo: 4 },
  { name: 'فارسی', enName: 'Persian', code: 'fa' },
  {
    name: 'Français',
    enName: 'French',
    code: 'fr',
    corePages: 'Pages Fondamentales',
    nextSteps: 'Étapes suivantes',
  },
  {
    name: 'ગુજરાતી',
    enName: 'Gujarati',
    code: 'gu',
  },
  { name: 'עברית', enName: 'Hebrew', code: 'he' },
  { name: 'हिन्दी', enName: 'Hindi', code: 'hi' },
  { name: 'Հայերեն', enName: 'Armenian', code: 'hy' },
  { name: 'Bahasa Indonesia', enName: 'Indonesian', code: 'id' },
  { name: 'Italiano', enName: 'Italian', code: 'it' },
  { name: '日本語', enName: 'Japanese', code: 'ja', issueNo: 4 },
  { name: '한국어', enName: 'Korean', code: 'ko' },
  { name: 'کوردی', enName: 'Kurdish', code: 'ku' },
  { name: 'മലയാളം', enName: 'Malayalam', code: 'ml' },
  { name: 'नेपाली', enName: 'Nepali', code: 'ne' },
  { name: 'Nederlands', enName: 'Dutch', code: 'nl' },
  { name: 'Polski', enName: 'Polish', code: 'pl' },
  { name: 'Português do Brasil', enName: 'Portuguese (Brazil)', code: 'pt-BR' },
  {
    name: 'Português europeu',
    enName: 'Portuguese (Portugal)',
    code: 'pt-PT',
  },
  { name: 'Română', enName: 'Romanian', code: 'ro' },
  { name: 'Русский', enName: 'Russian', code: 'ru' },
  { name: 'සිංහල', enName: 'Sinhala', code: 'si' },
  { name: 'தமிழ்', enName: 'Tamil', code: 'ta' },
  { name: 'Türkçe', enName: 'Turkish', code: 'tr' },
  { name: 'Українська', enName: 'Ukrainian', code: 'uk' },
  { name: 'Oʻzbekcha', enName: 'Uzbek', code: 'uz' },
  { name: 'Tiếng Việt', enName: 'Vietnamese', code: 'vi' },
  {
    name: '简体中文',
    enName: 'Simplified Chinese',
    code: 'zh-hans',
    issueNo: 4,
  },
  { name: '繁體中文', enName: 'Traditional Chinese', code: 'zh-hant' },
]
